### ISSUE TITLE
Remove Superset init container and replace with a k8s job

### ISSUE THREAD

**Issue by rimolive** [opendatahub-io/odh-manifests#211]
**Is your feature request related to a problem? Please describe.**
Currently, Superset initializes its database through `superset init` command that runs on an init container. This command also resets the configuration of default security Roles in case data is already populated and customized.

However, every time Superset pod starts the init container runs the init command again without considering data is already populated and customized. That leads to data loss when there is a custom configuration over default data.

**Describe the solution you'd like**
Ideally, this initialization should be made through a k8s Job object just like Hue does to initialize its database. With that, then the init container should run a loop to inspect if the database is already created and populated with data.

**Describe alternatives you've considered**
I don't see other options than the k8s Job, but other alternatives to fix that are welcome.

**Additional context**
N/A

**Comment by maulikjs** [comment]
This MR #426 moves the init job to an overlay.
So if we want to run the job we can call it from the kfdef

```
    - kustomizeConfig:
        overlays:
          - superset-init-job
        repoRef:
          name: manifests
          path: odh-manifests/superset
      name: superset
 ```
