### ISSUE TITLE
Grafana-operator 3.6 Datasource error

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/odh-manifests#231]
**Describe the bug**
Fresh deployment of master branch, with Grafana-operator updated to 3.6.
The Grafana pods are not deployed, with the operator pods throwing this error:
`E1104 20:56:41.643003       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1alpha1.GrafanaDataSource: v1alpha1.GrafanaDataSourceList.ListMeta: v1.ListMeta.TypeMeta: Kind: Items: []v1alpha1.GrafanaDataSource: v1alpha1.GrafanaDataSource.Status: v1alpha1.GrafanaDataSourceStatus.Phase: ReadString: expects " or n, but found 2, error found in #10 byte of ...|,"phase":2}}],"kind"|..., bigger context ...|nfig":"573375789963c240f2dff214c8a837da","phase":2}}],"kind":"GrafanaDataSourceList","metadata":{"co|...`

Apparently it is waiting for a string in the `status/phase` field, but gets a number (2). Here is the relevant part in the DataSource:
```
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
        tlsSkipVerify: true
      name: opendatahub
      type: prometheus
      url: 'http://prometheus-operated:9090'
      version: 1
  name: odh-prometheus.yaml
status:
  lastConfig: 573375789963c240f2dff214c8a837da
  phase: 2
```

**Open Data Hub Version**
0.8, with manifests from master

**OpenShift Version**
Version #: 4.5.7
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...): AWS

**Additional context**
Deployed multiple times. Could it be a leftover that puts "Phase: 2"
