### ISSUE TITLE
SPIKE: Monitoring multi namespace components other than where Prometheus is installed

### ISSUE THREAD

**Issue by anishasthana** [opendatahub-io/odh-manifests#234]
ODH Prometheus is currently unable to monitor components that are deployed in different namespaces. We need to figure out how to get it working, so a technical proposal would be ideal here.

**Comment by anishasthana** [comment]
cc @HumairAK @4n4nd

**Comment by HumairAK** [comment]
Okay so going to break down in detail what the issues that I'm encountering are: 

Goal: try to get prometheus to monitor components in a different namespace 

Currently if you try to install the prometheus operator via odh, it will use the operator group from [here](https://github.com/opendatahub-io/odh-manifests/blob/v0.8.0/odh-common/base/operatorgroup.yaml), notice the `- $(namespace)` this takes on the namespace upon which you install the prometheus operator (and odh-common). If I want prometheus to monitor another namespace (i.e. have the operator able to see the service monitors in another namespace), then I would need to append to this field in the operatorgroup's `spec.targetNamespaces`. There is one caveat however, in the ocp docs [here](https://docs.openshift.com/container-platform/4.6/operators/understanding/olm/olm-understanding-operatorgroups.html#olm-operatorgroups-target-namespace_olm-understanding-operatorgroups) it states the following: 

> Listing multiple namespaces via spec.targetNamespaces or use of a label selector via spec.selector is not recommended, as the support for more than one target namespace in an OperatorGroup will likely be removed in a future release.

So that's not recommended. Another option could be to have the operatorgroup set `spec.targetNamespaces ` to blank, this turns it into a global operator, which selects all namespaces. But when I try doing this I get the following `fail` error during prometheus operator installation (via odh): 
> Reason: InterOperatorGroupOwnerConflict
> Danger alert:Failed: intersecting operatorgroups provide the same apis

I've tried this on a blank ocp cluster with the folowing kfdef spec: 
```
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: opf-monitoring
        repoRef:
          name: manifests
          path: prometheus/cluster
      name: prometheus-cluster
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: opf-monitoring
        repoRef:
          name: manifests
          path: prometheus/operator
      name: prometheus-operator

    # Override odh-common
    - kustomizeConfig:
        repoRef:
          name: opf-overrides
          path: kfdef/odh-common
      name: odh-common
  repos:
    - name: manifests
      uri: "https://github.com/opendatahub-io/odh-manifests/tarball/v0.8.0"
    - name: opf-overrides
      uri: "https://github.com/humairak/odh/tarball/add_monitoring"
  version: v0.8.0
```
The override from `opf-overrides` is just replacing the odh-common [operatorgroup](https://github.com/opendatahub-io/odh-manifests/blob/v0.8.0/odh-common/base/operatorgroup.yaml) with the following: 

```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: opendatahub
```

If someone can get this working for cluster-wide namespace access for the prom operator please let us know how.
