### ISSUE TITLE
SPIKE: How to define a multi-namespace instance of ODH

### ISSUE THREAD

**Issue by vpavlin** [opendatahub-io/odh-manifests#236]
**Is your feature request related to a problem? Please describe.**
For production deployments we would like ODH to be deployed across multiple namespaces

Current approach to achieve this is to use multiple KFDefs - for each namespace one KFDef. We do not believe this is a good strategy long term since it complicates the deployment, management and monitoring and also complicates integrations between components.

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
TBD

**Additional context**

CC @tumido @HumairAK @anishasthana

**Comment by vpavlin** [comment]
We discussed this with @tumido and decided we would like to try the approach where a component will specify a `namespace` parameter if it should be deployed to a different namespace than where `KFdef` lives.

This means the user will end up with a single KFDef, which is one of the goals from the management perspective.

This solution also comes with problems though

1. Kubeflow operator will not create namespaces, so the namespaces defined in components either need to exist prior deployment, or a `namespace` manifest need to be added to the given component (e.g. [istio](https://github.com/kubeflow/manifests/blob/master/istio/istio-install/base/istio-noauth.yaml#L2)).
2. Each component needs to make sure it properly templates `namespace` in non-standard locations (e.g. [SA namespace in ClusterRoleBinding](https://github.com/kubeflow/manifests/blob/master/istio-1-3-1/istio-install-1-3-1/base/cluster-role-binding.yaml#L14)
3. We still need to figure out how to enable communication between components in different namespaces - this could be probably solved by Service Mesh in the future, but it might mean special NetworkPolicies for now

In the future, we'd like to propose a change to how a component `namespace` is defined and instead of it being a "magic" parameter, we'd like to see it as part of KFDef spec:

Current:

```
- kustomizeConfig:
      parameters:
      - name: namespace
        value: istio-system
      repoRef:
        name: manifests
        path: istio/istio-crds
```

Future:

```
- kustomizeConfig:
      namespace: istio-system
      repoRef:
        name: manifests
        path: istio/istio-crds
```
