### ISSUE TITLE
KF and ODH v0.9 mixing is broken for monitoring

### ISSUE THREAD

**Issue by nakfour** [opendatahub-io/odh-manifests#257]
**Describe the bug**
When running this example kfdef
```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: kubeflow
  namespace: kubeflow
spec:
  applications:
# This needs to be first to set up permissions
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/openshift/application/openshift/openshift-scc
    name: openshift-scc
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/openshift/application/istio-stack
    name: istio-stack
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/openshift/application/istio
    name: istio
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/v3
    name: application
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: metacontroller/base
    name: metacontroller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/openshift/application/cert-manager-crds
    name: cert-manager-crds
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/openshift/application/cert-manager-kube-system-resources
    name: cert-manager-kube-system-resources
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/openshift/application/cert-manager
    name: cert-manager
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/openshift/application/argo
    name: argo
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/openshift/application/jupyter-web-app
    name: jupyter-web-app
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/openshift/application/notebook-controller
    name: notebook-controller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/openshift/application/metadata
    name: metadata
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/openshift/application/tf-job
    name: tf-job
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/openshift/application/pytorch-job
    name: pytorch-job
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/openshift/application/katib
    name: katib
  # commenting this out since it is included in kubeflow-apps
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/openshift/application/pipeline
    name: pipeline
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/openshift/application/seldon
    name: seldon
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/openshift
    name: kubeflow-apps
  - kustomizeConfig:
      repoRef:
        name: odhmanifests
        path: prometheus/cluster
    name: prometheus-cluster
  - kustomizeConfig:
      overlays:
      - kubeflow
      repoRef:
        name: odhmanifests
        path: prometheus/operator
    name: prometheus-operator
  - kustomizeConfig:
      repoRef:
        name: odhmanifests
        path: grafana/cluster
    name: grafana-cluster
  - kustomizeConfig:
      repoRef:
        name: odhmanifests
        path: grafana/grafana
    name: grafana-instance
  repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/v1.2-branch.tar.gz
  - name: odhmanifests
    uri: https://github.com/opendatahub-io/odh-manifests/tarball/v0.9.0
  version: v0.9-branch-openshift
```
Error is listed below
```
Deploying application prometheus-cluster      filename="kustomize/kustomize.go:248"
ERRO[0041] Error evaluating kustomization manifest for prometheus-cluster: accumulating resources: couldn't make target for path '../../.cache/odhmanifests/opendatahub-io-odh-manifests-a56ccf2/prometheus/cluster': unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/Users/jnakfour/kubeflow/odh-kubeflow-fork/kubeflow11/kf11/.cache/odhmanifests/opendatahub-io-odh-manifests-a56ccf2/prometheus/cluster'  filename="kustomize/kustomize.go:155"
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for prometheus-cluster: accumulating resources: couldn't make target for path '../../.cache/odhmanifests/opendatahub-io-odh-manifests-a56ccf2/prometheus/cluster': unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/Users/jnakfour/kubeflow/odh-kubeflow-fork/kubeflow11/kf11/.cache/odhmanifests/opendatahub-io-odh-manifests-a56ccf2/prometheus/cluster'
```
**Steps To Reproduce**

**Expected behavior**

**Workaround (if any)**
Any manual steps that allow you to resolve the issue

**Open Data Hub Version**
Please attach relevant kfdef manifest if applicable

**OpenShift Version**
Version #: 
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...):

**Additional context**
