### ISSUE TITLE
Add "data-catalog" component to deploy hue and thriftserver components

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-manifests#269]
**Is your feature request related to a problem? Please describe.**
If user wants to use all of SQL features of the hue component it requires a  `HiveServer2 type of service` that requires the hue and thriftserver components with the same parameters defined

**Describe the solution you'd like**
To make it easier to deploy Hue (#227) and Thriftserver (#228) components together, we should provide a `data-catalog` "meta-component" that will deploy hue and thriftserver components
```
  # This config would deploy all of the hue and thriftserver defaults for overlays that make up the ODH data-catalog
  - kustomizeConfig:
      parameters:
        - name: spark_url
          value: "spark://spark-cluster-thriftserver"
          # This would be any S3 object store but using ceph-nano component as the example
        - name: s3_is_secure
          value: "false"
        - name: s3_endpoint_url
          value: "http://ceph-nano-0"
        - name: s3_credentials_secret
          value: ceph-nano-credentials
      repoRef:
        name: manifests
        path: data-catalog
    name: data-catalog
```

**Describe alternatives you've considered**
The default is the define them each separately in their own `kustomizeConfig` with parameters that have the same values

**Additional context**
