### ISSUE TITLE
Create a UI Configuration section to the main ConfigMap

### ISSUE THREAD

**Issue by mroman-redhat** [opendatahub-io/odh-manifests#320]
To be able to configure the UI to provide only the neccessary information and in a correct manner, a configuration structure needs to be applied such as:

```
images:
  visible: False
gpu:
  limit: 4
  style: "input"
---------------- or
gpu:
  style: "dropdown"
  values:
    - 0
    - 2
    - 4
---------------- or
gpu:
  style: "checkbox"
envvars:
  style: "limited"/"unlimited"
  variables(if limited):
    - "example1"
    - "example2"
```

That is to say, the admin should be able to set whether a component is visible, what style it has (if applicable). Environment variables could be limited for example and only pre-written, GPU could be set by either a dropdown, checkbox or input. And any component could be set to not appear in the UI if neccessary.
