### ISSUE TITLE
ODH manifest v1.0.5/1.0.6: JupyterHub  fails with HTTP 599: Peer's Certificate issuer is not recognized

### ISSUE THREAD

**Issue by ptitzler** [opendatahub-io/odh-manifests#357]
**Describe the bug**
After installation of ODH manifest v1.0.5 error `HTTP 599: Peer's Certificate issuer is not recognized.` is raised when a user tries to access JupyterHub.

**Steps To Reproduce**
1. Follow instructions in https://opendatahub.io/docs/getting-started/quick-installation
2. In step 5 I replaced the repository URI 
  ```
  repos:
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.0.5'
  version: v1.0.5
  ``` 
3. Open JupyterHub GUI. `500 : Internal Server Error` is displayed
4. The JupyterHub pod log contains the following:

```
---> Running application from script (/opt/app-root/builder/run) ...
+ trap 'kill -TERM $PID' TERM INT
+ PID=37
+ wait 37
+ start-jupyterhub.sh
+ set -eo pipefail
+ PATH=/opt/app-root/bin:/opt/rh/rh-python36/root/usr/bin:/opt/rh/rh-nodejs10/root/usr/bin:/opt/rh/httpd24/root/usr/bin:/opt/rh/httpd24/root/usr/sbin:/opt/app-root/src/.local/bin/:/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/app-root/scripts
+ . /opt/app-root/etc/jupyterhub_config.sh
++ '[' x '!=' x ']'
++ '[' -f /opt/app-root/src/.jupyter/jupyterhub_config.sh ']'
++ '[' -f /opt/app-root/configs/jupyterhub_config.sh ']'
+ jupyterhub upgrade-db -f /opt/app-root/etc/jupyterhub_config.py
[I 2021-03-22 20:00:58.402 alembic.runtime.migration migration:163] Context impl PostgresqlImpl.
[I 2021-03-22 20:00:58.403 alembic.runtime.migration migration:170] Will assume transactional DDL.
[I 2021-03-22 20:00:58.417 alembic.runtime.migration migration:555] Running stamp_revision  -> 4dc2d5a8c53c
+ exec jupyterhub -f /opt/app-root/etc/jupyterhub_config.py
[I 2021-03-22 20:01:00.390 JupyterHub app:2349] Running JupyterHub version 1.3.0
[I 2021-03-22 20:01:00.391 JupyterHub app:2380] Using Authenticator: oauthenticator.openshift.OpenShiftOAuthenticator-0.13.1dev
[I 2021-03-22 20:01:00.391 JupyterHub app:2380] Using Spawner: builtins.OpenShiftSpawner
[I 2021-03-22 20:01:00.391 JupyterHub app:2380] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.3.0
[I 2021-03-22 20:01:00.393 JupyterHub app:1416] Loading cookie_secret from env[JPY_COOKIE_SECRET]
[D 2021-03-22 20:01:00.393 JupyterHub app:1587] Connecting to db: postgresql://jupyterhub:[redacted]@jupyterhub-db:5432/jupyterhub
[D 2021-03-22 20:01:00.447 JupyterHub orm:784] Stamping empty database with alembic revision 4dc2d5a8c53c
[I 2021-03-22 20:01:00.464 alembic.runtime.migration migration:163] Context impl PostgresqlImpl.
[I 2021-03-22 20:01:00.464 alembic.runtime.migration migration:170] Will assume transactional DDL.
[I 2021-03-22 20:01:00.692 JupyterHub app:1726] Not using allowed_users. Any authenticated user will be allowed.
[I 2021-03-22 20:01:00.777 JupyterHub app:1848] Adding API token for service: prometheus
[D 2021-03-22 20:01:00.788 JupyterHub app:1877] Purging expired APITokens
[D 2021-03-22 20:01:00.794 JupyterHub app:1877] Purging expired OAuthAccessTokens
[D 2021-03-22 20:01:00.799 JupyterHub app:1877] Purging expired OAuthCodes
[D 2021-03-22 20:01:00.814 JupyterHub app:2004] Initializing spawners
[D 2021-03-22 20:01:00.823 JupyterHub app:2137] Loaded users:
    
[I 2021-03-22 20:01:00.824 JupyterHub app:2419] Initialized 0 spawners in 0.010 seconds
[W 2021-03-22 20:01:00.827 JupyterHub proxy:663] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2021-03-22 20:01:00.827 JupyterHub proxy:666] Starting proxy @ http://:8080/
[D 2021-03-22 20:01:00.827 JupyterHub proxy:667] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8080', '--api-ip', '127.0.0.1', '--api-port', '8082', '--error-target', 'http://jupyterhub:8081/hub/error']
[D 2021-03-22 20:01:00.834 JupyterHub proxy:574] Writing proxy pid file: jupyterhub-proxy.pid
20:01:01.167 [ConfigProxy] info: Proxying http://*:8080 to (no default)
20:01:01.170 [ConfigProxy] info: Proxy API at http://127.0.0.1:8082/api/routes
[D 2021-03-22 20:01:01.283 JupyterHub proxy:702] Proxy started and appears to be up
[D 2021-03-22 20:01:01.285 JupyterHub proxy:795] Proxy: Fetching GET http://127.0.0.1:8082/api/routes
20:01:01.305 [ConfigProxy] info: 200 GET /api/routes 
[I 2021-03-22 20:01:01.307 JupyterHub app:2664] Hub API listening on http://0.0.0.0:8081/hub/
[I 2021-03-22 20:01:01.308 JupyterHub app:2666] Private Hub API connect url http://jupyterhub:8081/hub/
[I 2021-03-22 20:01:01.308 JupyterHub app:2679] Starting managed service public
[I 2021-03-22 20:01:01.309 JupyterHub service:339] Starting service 'public': ['bash', '-c', 'jupyter_publish_service']
[I 2021-03-22 20:01:01.313 JupyterHub service:121] Spawning bash -c jupyter_publish_service
[D 2021-03-22 20:01:01.320 JupyterHub spawner:1147] Polling subprocess every 30s
[I 2021-03-22 20:01:01.323 JupyterHub app:2679] Starting managed service jsp-api at http://127.0.0.1:8181
[I 2021-03-22 20:01:01.323 JupyterHub service:339] Starting service 'jsp-api': ['jupyterhub-singleuser-profiles-api']
[I 2021-03-22 20:01:01.327 JupyterHub service:121] Spawning jupyterhub-singleuser-profiles-api
[D 2021-03-22 20:01:01.332 JupyterHub spawner:1147] Polling subprocess every 30s
/opt/app-root/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.21.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/opt/app-root/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.21.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/opt/app-root/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.21.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/opt/app-root/lib/python3.6/site-packages/jupyterhub_singleuser_profiles/profiles.py:86: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_map_yaml = yaml.load(config_map.data[key_name])
The swagger_ui directory could not be found.
    Please install connexion with extra install: pip install connexion[swagger-ui]
    or provide the path to your local installation by passing swagger_path=<your path>

The swagger_ui directory could not be found.
    Please install connexion with extra install: pip install connexion[swagger-ui]
    or provide the path to your local installation by passing swagger_path=<your path>

 * Serving Flask app "jupyterhub_singleuser_profiles.api.api" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8181/ (Press CTRL+C to quit)
127.0.0.1 - - [22/Mar/2021 20:01:03] "GET /services/jsp-api/ HTTP/1.1" 404 -
[D 2021-03-22 20:01:03.241 JupyterHub utils:224] Server at http://127.0.0.1:8181/services/jsp-api/ responded with 404
[I 2021-03-22 20:01:03.241 JupyterHub app:2688] Adding external service prometheus
[D 2021-03-22 20:01:03.241 JupyterHub proxy:314] Fetching routes to check
[D 2021-03-22 20:01:03.241 JupyterHub proxy:795] Proxy: Fetching GET http://127.0.0.1:8082/api/routes
20:01:03.244 [ConfigProxy] info: 200 GET /api/routes 
[I 2021-03-22 20:01:03.244 JupyterHub proxy:319] Checking routes
[I 2021-03-22 20:01:03.244 JupyterHub proxy:399] Adding default route for Hub: / => http://jupyterhub:8081
[W 2021-03-22 20:01:03.248 JupyterHub proxy:373] Adding missing route for jsp-api (Server(url=http://127.0.0.1:8181/services/jsp-api/, bind_url=http://127.0.0.1:8181/services/jsp-api/))
[I 2021-03-22 20:01:03.250 JupyterHub proxy:242] Adding service jsp-api to proxy /services/jsp-api/ => http://127.0.0.1:8181
[D 2021-03-22 20:01:03.252 JupyterHub proxy:795] Proxy: Fetching POST http://127.0.0.1:8082/api/routes/services/jsp-api
[D 2021-03-22 20:01:03.252 JupyterHub proxy:795] Proxy: Fetching POST http://127.0.0.1:8082/api/routes/
20:01:03.255 [ConfigProxy] info: Adding route /services/jsp-api -> http://127.0.0.1:8181
20:01:03.257 [ConfigProxy] info: Route added /services/jsp-api -> http://127.0.0.1:8181
20:01:03.257 [ConfigProxy] info: 201 POST /api/routes/services/jsp-api 
20:01:03.293 [ConfigProxy] info: Adding route / -> http://127.0.0.1:8081
20:01:03.294 [ConfigProxy] info: Route added / -> http://127.0.0.1:8081
20:01:03.294 [ConfigProxy] info: 201 POST /api/routes/ 
[I 2021-03-22 20:01:03.296 JupyterHub app:2739] JupyterHub is now running at http://:8080/
[D 2021-03-22 20:01:03.297 JupyterHub app:2342] It took 3.554 seconds for the Hub to start
20:01:06.667 [ConfigProxy] info: 200 GET /api/routes 
20:01:11.676 [ConfigProxy] info: 200 GET /api/routes 
20:01:16.688 [ConfigProxy] info: 200 GET /api/routes 
20:01:21.698 [ConfigProxy] info: 200 GET /api/routes 
20:01:26.706 [ConfigProxy] info: 200 GET /api/routes 
[I 2021-03-22 20:01:27.142 JupyterHub log:181] 302 GET / -> /hub/ (@::ffff:172.30.86.68) 1.86ms
[I 2021-03-22 20:01:27.163 JupyterHub log:181] 302 GET /hub/ -> /hub/login?next=%2Fhub%2F (@::ffff:172.30.86.68) 0.84ms
[I 2021-03-22 20:01:27.195 JupyterHub log:181] 302 GET /hub/login?next=%2Fhub%2F -> /hub/oauth_login?next=%2Fhub%2F (@::ffff:172.30.86.68) 1.64ms
[I 2021-03-22 20:01:27.216 JupyterHub oauth2:104] OAuth redirect: 'https://jupyterhub-105-test.ptitzler-odh-442dbba0442be6c8c50f31ed96b00601-0000.sjc04.containers.appdomain.cloud/hub/oauth_callback'
[D 2021-03-22 20:01:27.217 JupyterHub base:521] Setting cookie oauthenticator-state: {'httponly': False, 'expires_days': 1}
[I 2021-03-22 20:01:27.240 JupyterHub log:181] 302 GET /hub/oauth_login?next=%2Fhub%2F -> https://c104-e.us-south.containers.cloud.ibm.com:31353/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fjupyterhub-105-test.ptitzler-odh-442dbba0442be6c8c50f31ed96b00601-0000.sjc04.containers.appdomain.cloud%2Fhub%2Foauth_callback&client_id=system%3Aserviceaccount%3A105-test%3Ajupyterhub-hub&state=[secret]&scope=user%3Ainfo (@::ffff:172.30.86.68) 24.51ms
20:01:31.717 [ConfigProxy] info: 200 GET /api/routes 
[E 2021-03-22 20:01:33.448 JupyterHub web:1793] Uncaught exception GET /hub/oauth_callback?code=ATwGHk4AP1iAv3hR2Srn51Kcfr77LU2KjiTP8GGwgoQ&state=eyJzdGF0ZV9pZCI6ICI0MzlmNmVlMjAxOWE0NDBhYjU1M2FhMjJmODY5ZDAyZSIsICJuZXh0X3VybCI6ICIvaHViLyJ9 (::ffff:172.30.86.68)
    HTTPServerRequest(protocol='http', host='jupyterhub-105-test.ptitzler-odh-442dbba0442be6c8c50f31ed96b00601-0000.sjc04.containers.appdomain.cloud', method='GET', uri='/hub/oauth_callback?code=ATwGHk4AP1iAv3hR2Srn51Kcfr77LU2KjiTP8GGwgoQ&state=eyJzdGF0ZV9pZCI6ICI0MzlmNmVlMjAxOWE0NDBhYjU1M2FhMjJmODY5ZDAyZSIsICJuZXh0X3VybCI6ICIvaHViLyJ9', version='HTTP/1.1', remote_ip='::ffff:172.30.86.68')
    Traceback (most recent call last):
      File "/opt/app-root/lib/python3.6/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/app-root/src/oauthenticator/oauthenticator/oauth2.py", line 224, in get
        user = await self.login_user()
      File "/opt/app-root/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 749, in login_user
        authenticated = await self.authenticate(data)
      File "/opt/app-root/lib/python3.6/site-packages/jupyterhub/auth.py", line 462, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/opt/app-root/src/oauthenticator/oauthenticator/openshift.py", line 130, in authenticate
        resp = await http_client.fetch(req)
    tornado.curl_httpclient.CurlError: HTTP 599: Peer's Certificate issuer is not recognized.
    
[D 2021-03-22 20:01:33.452 JupyterHub base:1280] No template for 500
[E 2021-03-22 20:01:33.499 JupyterHub log:173] {
      "X-Forwarded-For": "10.87.76.76,::ffff:172.30.86.68",
      "Forwarded": "for=10.87.76.76;host=jupyterhub-105-test.ptitzler-odh-442dbba0442be6c8c50f31ed96b00601-0000.sjc04.containers.appdomain.cloud;proto=https",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "jupyterhub-105-test.ptitzler-odh-442dbba0442be6c8c50f31ed96b00601-0000.sjc04.containers.appdomain.cloud",
      "Host": "jupyterhub-105-test.ptitzler-odh-442dbba0442be6c8c50f31ed96b00601-0000.sjc04.containers.appdomain.cloud",
      "Cookie": "oauthenticator-state=[secret]",
      "Accept-Language": "en-US,en;q=0.9,de;q=0.8",
      "Accept-Encoding": "gzip, deflate, br",
      "Referer": "https://c104-e.us-south.containers.cloud.ibm.com:31353/",
      "Sec-Ch-Ua-Mobile": "?0",
      "Sec-Ch-Ua": "\"Google Chrome\";v=\"89\", \"Chromium\";v=\"89\", \";Not A Brand\";v=\"99\"",
      "Sec-Fetch-Dest": "document",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-Site": "cross-site",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Cache-Control": "max-age=0",
      "Connection": "close"
    }
[E 2021-03-22 20:01:33.499 JupyterHub log:181] 500 GET /hub/oauth_callback?code=[secret]&state=[secret] (@::ffff:172.30.86.68) 250.40ms
[D 2021-03-22 20:01:33.571 JupyterHub log:181] 200 GET /hub/static/css/style.min.css?v=a690a7f26f8eda24b6043d972eda379b7f3df65dcb4832fbec0d72d1585b6bdf2bd15c7f3ec4597b79a7c91798181ba23b9a0204da8165b21ff81cd85f89a933 (@::ffff:172.30.86.68) 1.82ms
[D 2021-03-22 20:01:33.576 JupyterHub log:181] 200 GET /hub/static/components/requirejs/require.js?v=bd1aa102bdb0b27fbf712b32cfcd29b016c272acf3d864ee8469376eaddd032cadcf827ff17c05a8c8e20061418fe58cf79947049f5c0dff3b4f73fcc8cad8ec (@::ffff:172.30.27.91) 1.01ms
[D 2021-03-22 20:01:33.628 JupyterHub log:181] 200 GET /hub/static/components/jquery/dist/jquery.min.js?v=6cb4f4426f559c06190df97229c05a436820d21498350ac9f118a5625758435171418a022ed523bae46e668f9f8ea871feab6aff58ad2740b67a30f196d65516 (@::ffff:172.30.86.68) 2.20ms
[D 2021-03-22 20:01:33.635 JupyterHub log:181] 200 GET /hub/static/components/bootstrap/dist/js/bootstrap.min.js?v=a014e9acc78d10a0a7a9fbaa29deac6ef17398542d9574b77b40bf446155d210fa43384757e3837da41b025998ebfab4b9b6f094033f9c226392b800df068bce (@::ffff:172.30.27.91) 0.91ms
[D 2021-03-22 20:01:33.673 JupyterHub log:181] 200 GET /hub/logo (@::ffff:172.30.27.91) 1.30ms
[D 2021-03-22 20:01:33.733 JupyterHub log:181] 200 GET /hub/static/favicon.ico?v=fde5757cd3892b979919d3b1faa88a410f28829feb5ba22b6cf069f2c6c98675fceef90f932e49b510e74d65c681d5846b943e7f7cc1b41867422f0481085c1f (@::ffff:172.30.27.91) 1.29ms
20:01:36.733 [ConfigProxy] info: 200 GET /api/routes 

```

**Expected behavior**

**Open Data Hub Version**
Please attach relevant kfdef manifest if applicable
Operator version: 1.0.0
KfDef version: 

**OpenShift Version**
Version #: 4.5.31_1531
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...): IBM Cloud

**Additional context**

**Comment by ptitzler** [comment]
Manifest version 1.0.0 results in the error reported in https://github.com/opendatahub-io/odh-manifests/issues/319

**Comment by ptitzler** [comment]
Manifest version 0.9.0 works fine.

**Comment by ptitzler** [comment]
For reference the `KfDef` I was referring ("In step 5 ...") to looks as follows:

```
   # ODH uses the KfDef manifest format to specify what components will be included in the deployment
   apiVersion: kfdef.apps.kubeflow.org/v1
   kind: KfDef
   metadata:
     # The name of your deployment
     name: opendatahub
   # only the components listed in the `KFDef` resource will be deployed:
   spec:
     applications:
       # REQUIRED: This contains all of the common options used by all ODH components
       - kustomizeConfig:
           repoRef:
             name: manifests
             path: odh-common
         name: odh-common
       # Deploy Radanalytics Spark Operator
       - kustomizeConfig:
           repoRef:
             name: manifests
             path: radanalyticsio/spark/cluster
         name: radanalyticsio-spark-cluster
       # Deploy Open Data Hub JupyterHub
       - kustomizeConfig:
           parameters:
             - name: s3_endpoint_url
               value: s3.odh.com
           repoRef:
             name: manifests
             path: jupyterhub/jupyterhub
         name: jupyterhub
       # Deploy addtional Open Data Hub Jupyter notebooks
       - kustomizeConfig:
           overlays:
             - additional
           repoRef:
             name: manifests
             path: jupyterhub/notebook-images
         name: notebook-images
     # Reference to all of the git repo archives that contain component kustomize manifests
     repos:
       # Official Open Data Hub v0.9.0 component manifests repo
       # This shows that we will be deploying components from an archive of the odh-manifests repo tagged for v0.9.0
       - name: manifests
         uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v0.9.0'
     version: v0.9-branch-openshift
```
