### ISSUE TITLE
ODH manifest 1.0.6 JupyterHub Spawner: no images are defined

### ISSUE THREAD

**Issue by ptitzler** [opendatahub-io/odh-manifests#366]
**Describe the bug**
A clear and concise description of what the bug is and how often it occurs

The JupyterHub spawner dialog displays no notebook images.
![image](https://user-images.githubusercontent.com/13068832/112528869-e481fb80-8d61-11eb-9626-f7572b443a99.png)

**Steps To Reproduce**
1. Create a new project
2. Create a new ODH instance in the project
3. Deploy the JupyterHub component using 1.0.6 manifests
```
  repos:
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.0.6'
  version: v1.0.6
```
5. Apply workaround for https://github.com/opendatahub-io/odh-manifests/issues/357
6. Open JupyterHub web console

**Expected behavior**
User can select from a  list of "notebook" images.

**Open Data Hub Version**
Please attach relevant kfdef manifest if applicable

```
# ODH uses the KfDef manifest format to specify what components will be included in the deployment
   apiVersion: kfdef.apps.kubeflow.org/v1
   kind: KfDef
   metadata:
     # The name of your deployment
     name: opendatahub
   # only the components listed in the `KFDef` resource will be deployed:
   spec:
     applications:
       # REQUIRED: This contains all of the common options used by all ODH components
       - kustomizeConfig:
           repoRef:
             name: manifests
             path: odh-common
         name: odh-common
       # Deploy Open Data Hub JupyterHub
       - kustomizeConfig:
           parameters:
             - name: s3_endpoint_url
               value: s3.odh.com
           repoRef:
             name: manifests
             path: jupyterhub/jupyterhub
         name: jupyterhub
       # Deploy addtional Open Data Hub Jupyter notebooks
       - kustomizeConfig:
           overlays:
             - additional
           repoRef:
             name: manifests
             path: jupyterhub/notebook-images
         name: notebook-images
     # Reference to all of the git repo archives that contain component kustomize manifests
     repos:
       # Official Open Data Hub v0.9.0 component manifests repo
       # This shows that we will be deploying components from an archive of the odh-manifests repo tagged for v0.9.0
       - name: manifests
         uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.0.6'
     version: v1.0.6
```

**OpenShift Version**
Version #: 4.5.31_1531
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...): IBM Cloud

**Additional context**
