### ISSUE TITLE
JupyterHub allowed_groups `""` causing Forbidden

### ISSUE THREAD

**Issue by tumido** [opendatahub-io/odh-manifests#369]
**Describe the bug**
Changes introduced in https://github.com/opendatahub-io/odh-manifests/pull/342 cause Forbidden error for all users if a custom configmap is used

**Steps To Reproduce**
1. Change `jupyterhub-groups-configmap.yaml` to have `admin_groups` set to a group and `allowed_groups` set to empty:
   ```yaml
   apiVersion: v1
   kind: ConfigMap
   metadata:
     labels:
       app: jupyterhub
     name: jupyterhub-default-groups-config
   data:
     admin_groups: "operate-first"
     allowed_groups: ""
   ```
2. Deploy
3. Try to log in

**Expected behavior**
works out of the box as described in the documentation

**Workaround (if any)**
set `allowed_users` to `system:authenticated`

**Open Data Hub Version**
1.0.5

**OpenShift Version**
4.7

**Additional context**
https://github.com/operate-first/support/issues/161
