### ISSUE TITLE
odh-common: OperatorGroup targetnamespace is not updated when opendatahub is deployed to a custom namespace

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-manifests#38]
Changing the namespace for deploying opendatahub does not update the namespace specified in `.spec.targetNamespaces`

I was overriding the kfdef namespace by setting
```yaml
kind: kfdef
metadata:
  namespace: foobar
```
