### ISSUE TITLE
ODH gets stuck deploying Seldon operator

### ISSUE THREAD

**Issue by mamurak** [opendatahub-io/odh-manifests#552]
**Describe the bug**
After instantiating a new KfDef including `odh-seldon`, the ODH operator is unable to deploy the Seldon operator. A subscription for the Seldon operator is created, but the operator itself is not installed.

**Steps To Reproduce**
1. Install ODH operator
2. Instantiate KfDef with `odh-seldon` entry (sample below) in empty namespace.
3. Monitor `Installed Operators` tab.
4. The `seldon-operator-certified` entry is created, but the Seldon operator is not installed.

**Expected behavior**
The Seldon operator should be installed and updated to the latest release.

**Workaround (if any)**
In deployed `seldon-operator-certified` subscription, change value of `spec.startingCSV` from `seldon-operator.v1.7.0` to `seldon-operator.v1.13.1`.

**Open Data Hub Version**
ODH 1.1.2. Sample KfDef below.

**OpenShift Version**
Version #: 4.8
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...): AWS

**Additional context**
Sample KfDef:
```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
  namespace: odh-seldon
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odhseldon/cluster
      name: odhseldon
  repos:
    - name: kf-manifests
      uri: >-
        https://github.com/opendatahub-io/manifests/tarball/v1.4.0-rc.2-openshift
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.1.2'
status: {}
```

**Comment by mamurak** [comment]
I've observed this piece of the `seldon-operator-certified` package manifest, which might be related to this issue:
```
status
  catalogSource: certified-operators
  catalogSourceDisplayName: Certified Operators
  catalogSourcePublisher: Red Hat
  catalogSourceNamespace: openshift-marketplace
  provider:
    name: Seldon Technologies
  packageName: seldon-operator-certified
  channels:
    - name: stable
      currentCSV: seldon-operator.v1.13.1
      currentCSVDesc:
        annotations:
          olm.skipRange: <1.12.0
```

The `odh-seldon` subscription shipped with ODH contains version 1.7.0, so if OLM skips version below 1.12.0, the Seldon operator subscription might be ignored during ODH instantiation.
