### ISSUE TITLE
Traefik Proxy pods fail to start due to missing configmap

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/odh-manifests#559]
**Describe the bug**
I am having problems with a missing traefik-rules configmap. Using ODH Operator 1.2.0 on Openshift 4.8.
I cannot access Jupyterhub because the traefik-proxy pods keep on restarting.

https://github.com/opendatahub-io/odh-manifests/search?q=traefik-rules

Configmap traefik-config is present, but configmap traefik-rules is not present in my namespace.

As a result, traefik-pods keep on restarting. 

Log configmap-puller:

```
2022/05/06 08:02:02 [/usr/local/bin/configmap-puller -outfile-name=/watched/rules.toml -configmap-name=traefik-rules -configmap-namespace=odhsven -configmap-key=rules.toml]
2022/05/06 08:02:02 kubeconfig
2022/05/06 08:02:02 configmapName traefik-rules
2022/05/06 08:02:02 configmapNamespace odhsven
2022/05/06 08:02:02 configmapKey rules.toml
2022/05/06 08:02:02 outfileName /watched/rules.toml
2022/05/06 08:02:02
2022/05/06 08:03:03 tick at: 2022-05-06 08:03:03.0383528 +0000 UTC m=+60.704876280
panic: configmaps "traefik-rules" not found

goroutine 1 [running]:
main.main()
	/src/cmd/configmap-puller/main.go:81 +0xad3
```

**Steps To Reproduce**

**Expected behavior**
Traefik-Proxy Pods start correctly.

**Workaround (if any)**
Any manual steps that allow you to resolve the issue

**Open Data Hub Version**
1.2.0
```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
  namespace: odhsven
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odhseldon/cluster
    name: odhseldon
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: superset
    name: superset
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: openshift-operators
      repoRef:
        name: manifests
        path: kafka/cluster
    name: strimzi-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: kafka/kafka
    name: kafka-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: grafana/cluster
    name: grafana-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: grafana/grafana
    name: grafana-instance
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: radanalyticsio/spark/cluster
    name: radanalyticsio-spark-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: prometheus/cluster
    name: prometheus-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: prometheus/operator
    name: prometheus-operator
  - kustomizeConfig:
      parameters:
        - name: s3_endpoint_url
          value: "s3.odh.com"
      repoRef:
        name: manifests
        path: jupyterhub/jupyterhub
    name: jupyterhub
  - kustomizeConfig:
      overlays:
      #- cuda-11.0.3
      - additional
      repoRef:
        name: manifests
        path: jupyterhub/notebook-images
    name: notebook-images
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: airflow/operator
    name: airflow-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: airflow/cluster
    name: airflow-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odhargo/cluster
    name: odhargo-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odhargo/odhargo
    name: odhargo
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: model-mesh
    name: model-mesh
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-dashboard
    name: odh-dashboard
  repos:
  - name: kf-manifests
    uri: https://github.com/opendatahub-io/manifests/tarball/v1.4.0-rc.2-openshift
  - name: manifests
    uri: https://github.com/opendatahub-io/odh-manifests/tarball/master
  version: master
```

**OpenShift Version**
Version #: 4.8.37
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...): Baremetal

**Additional context**
