### ISSUE TITLE
Reference db image by digest instead of tag

### ISSUE THREAD

**Issue by Zveroloff** [opendatahub-io/odh-manifests#567]
**Is your feature request related to a problem? Please describe.**
Currently, container image for jupyterhub-db pod is being pulled by tag. Pulling by tag does not respect ImageContentSourcePolicy, which makes it impossible to deploy ODH in completely airgapped environment with mirror registry.

**Describe the solution you'd like**
Possible solution is to change image reference to digest. Digest referenced images respect ICSP and works with mirror registry.

**Describe alternatives you've considered**
I don't see any alternative solutions for airgapped environments

**Additional context**
```
    spec:
      containers:
      - image: registry.redhat.io/rhel8/postgresql-96
        env:
        - name: POSTGRESQL_USER
          value: jupyterhub
        - name: POSTGRESQL_PASSWORD
```
