### ISSUE TITLE
odh-model-controller fails with OOMKilled

### ISSUE THREAD

**Issue by whanschke** [opendatahub-io/odh-manifests#704]
We tried installing the Open Data Hub operator on our Openshift Platform and the 3 pods of the odh-model-controller have the exit code 137 OOMKilled. Where do we need to increase the memory setting?

**Comment by srmeier** [comment]
I also ran into this issue. To address it I doubled the amount of memory for the `odh-model-controller` [here](https://github.com/opendatahub-io/odh-manifests/blob/master/model-mesh/overlays/odh-model-controller/manager/manager.yaml) down at the bottom.

**Comment by lokesh-sreedhara** [comment]
Ran into the same Error, Looks like oddh-moodel-controller is crashing due to OOMKilled 

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/110647904/231152985-c42c95af-5ae7-4212-92d5-53a56dbfb0f4.png">

**Comment by Jooho** [comment]
@lokesh-sreedhara Thanks for reporting. 
Could you please share the steps on how you install the modelserving?

**Comment by lokesh-sreedhara** [comment]
I jus followed the avaliable doc, Installed ODH catalog from Openshift Marketplace. then applied the default kfdef CR to install kubeflow. 

I think it does not like the Resource limits applied by default via the model-controller deployment. 

```
            limits:
              cpu: '1'
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 128Mi
```
