### ISSUE TITLE
odh dashboard not starting

### ISSUE THREAD

**Issue by whanschke** [opendatahub-io/odh-manifests#705]
**Describe the bug**
The odh dashboard is not visible, it blinks briefly when going to the browser but then vanishes completely.
in the odh dashboard pod the following message is displayed
{"level":40,"time":1668773538559,"pid":108,"hostname":"odh-dashboard-ccd4b7897-tg2g4","msg":"Received error (odhdashboardconfigs.opendatahub.io \"odh-dashboard-config\" not found) fetching OdhDashboardConfig, creating new."}

**Open Data Hub Version**
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  creationTimestamp: '2022-11-18T12:11:41Z'
  finalizers:
    - kfdef-finalizer.kfdef.apps.kubeflow.org
  generation: 2
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        overlays:
          - authentication
        repoRef:
          name: manifests
          path: odh-dashboard
      name: odh-dashboard
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-notebook-controller
      name: odh-notebook-controller
    - kustomizeConfig:
        overlays:
          - odh-model-controller
        repoRef:
          name: manifests
          path: model-mesh
      name: model-mesh
    - kustomizeConfig:
        overlays:
          - metadata-store-mariadb
          - ds-pipeline-ui
          - object-store-minio
          - default-configs
        repoRef:
          name: manifests
          path: data-science-pipelines
      name: ds-pipelines
    - kustomizeConfig:
        overlays:
          - additional
        repoRef:
          name: manifests
          path: jupyterhub/notebook-images
      name: notebook-images
  repos:
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.4'
status: {}

**OpenShift Version**
Version #: 4.11.13
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...): RedHat

**Comment by hvpareja** [comment]
Hi, I could reproduce the same issue in the same environment:

I have deployed ODH on my OCP cluster v4.11.13. Using the following minimalistic spec:

```
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        overlays:
          - authentication
        repoRef:
          name: manifests
          path: odh-dashboard
      name: odh-dashboard
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-notebook-controller
      name: odh-notebook-controller
    - kustomizeConfig:
        overlays:
          - additional
        repoRef:
          name: manifests
          path: jupyterhub/notebook-images
      name: notebook-images
  repos:
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.4'
 ```
 
Once everything was deployed, I tried to open the ODH dashboard in the browser but after loading during a couple of seconds it results in an empty white screen.
To be honest, I don’t know how to troubleshot this problem. Have anyone seen it before? Could you help me out?
Thanks!!
