### ISSUE TITLE
Provide an odh-core kustomize manifest to deploy all of the odh-core components using a single manifest

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-manifests#735]
**Is your feature request related to a problem? Please describe.**
The current kfdef to deploy [odh-core](https://github.com/opendatahub-io/odh-manifests/blob/master/kfdef/odh-core.yaml) requires 10 `kustomizeConfig` objects to deploy the odh-core components which can be confusing for new users that want to deploy odh-core with no changes to the defaults

**Describe the solution you'd like**
It would be helpful to simplify the process of deploying `odh-core` components with default configurations by adding an `odh-core` kustomize manifest that would deploy the odh-core components.  

```yaml
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-core
    name: odh-core
```

**Describe alternatives you've considered**
N/A

**Additional context**
This manifest would not require any changes to component manifests.  It should serve as a single install point to trigger deployments of the odh core manifest components
