### ISSUE TITLE
Storage class not set on PVC for Jupyter Notebook

### ISSUE THREAD

**Issue by linearlyIndependent** [opendatahub-io/odh-manifests#738]
**Describe the bug**
We deployed the ODH Operator (v1.4.1) on our OKD 4.11 cluster using the OperatorHub. We created the Open Data Hub instance (KfDef) using the specs below. We made our own fork of the this manifest repo and added our modifications to it: replaced some image references (from redhat.io to quay.io or cluster internal registry), some container limits, and most importantly the storage class definitions. 

I grepped the whole repo for any occurrence of "class, storage_class, etc.", and configured the required storage class. Despite this, when I deploy a Jupyter Notebook Server from the ODH Dashboard (Applications > Enabled > Jupyter - Launch Application > leaving everything on default > Start server) the Notebook creates a PVC where the storageClassName definition is missing. 

Since we don't have a default storage class in our cluster, the PVC will never bind. Even if we had a default, we still would want to use the storage class we defined.

**Steps To Reproduce**
1. Create odh Project
2. Install ODH Operator
3. Create an Open Data Hub instance (KfDef), based on a manifest where the storage class was set at (hopefully) all places where it could be set.
4. Wait until everything deploys.
5. Open the ODH Dashboard in the Browser
6. Deploy a Jupyter Notebook: Applications > Enabled > Jupyter - Launch Application > leaving everything on default > Start server
7. Notebook deployment fails because the generated PVC is missing the defined storageClassName and cannot bind.

**Expected behavior**
The deployment creates a PVC with the right storageClassName, the PVC is bound and the deployment completes successfully.

**Workaround (if any)**
Delete PVC, create a new PVC with the same parameters but with storageClassName set, deploy notebook again. This time the Notebook deploys successfully.

**Open Data Hub Version**
ODH Operator v1.4.1, from the Community Repo
Manifest v1.4.1, with some changes (see .diff file).

**OpenShift Version**
Version (OKD): 4.11.0-0.okd-2023-01-14-152430 
Provider : Baremetal/KVM

**Additional context**

**kfdef-opendatahub.yaml**
```yaml
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
  namespace: odh
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        overlays:
          - authentication
        repoRef:
          name: manifests
          path: odh-dashboard
      name: odh-dashboard
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-notebook-controller
      name: odh-notebook-controller
    - kustomizeConfig:
        overlays:
          - additional
        repoRef:
          name: manifests
          path: jupyterhub/notebook-images
      name: notebook-images
    - kustomizeConfig:
        overlays:
          - odh-model-controller
        repoRef:
          name: manifests
          path: model-mesh
      name: model-mesh
    - kustomizeConfig:
        overlays:
          - storage-class
        parameters:
          - name: storage_class
            value: nfs-research
        repoRef:
          name: manifests
          path: jupyterhub/jupyterhub
      name: jupyterhub
    - kustomizeConfig:
        overlays:
          - metadata-store-mariadb
          - ds-pipeline-ui
          - object-store-minio
          - default-configs
        repoRef:
          name: manifests
          path: data-science-pipelines
      name: data-science-pipelines
  repos:
    - name: manifests
      uri: >-
        https://<our-internal-git-server>/<group>/<clone-of-odh-manifests-repo>/-/archive/<our-release>/<our-release>.tar.gz
```

**PVC:**
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyterhub-nb-<user>-pvc
  namespace: odh
  uid: a42a94d4-5894-4a2e-a629-bc2147c3e17c
  resourceVersion: '313203356'
  creationTimestamp: '2023-02-23T16:14:19Z'
  labels:
    opendatahub.io/dashboard: 'true'
  finalizers:
    - kubernetes.io/pvc-protection
  managedFields:
    - manager: unknown
      operation: Update
      apiVersion: v1
      time: '2023-02-23T16:14:19Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:opendatahub.io/dashboard': {}
        'f:spec':
          'f:accessModes': {}
          'f:resources':
            'f:requests':
              .: {}
              'f:storage': {}
          'f:volumeMode': {}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '20'
  volumeMode: Filesystem
  # storageClassName is missing, if PVC is recreated with it,  the deployment succeeds
  #storageClassName: nfs-research
status:
  phase: Pending

```

**diff to your v1.4.1 manifest release (a is your version, b is ours):**
```diff
diff --git a/data-science-pipelines/overlays/ds-pipeline-ui/deployments/ds-pipeline-ui.yaml b/data-science-pipelines/overlays/ds-pipeline-ui/deployments/ds-pipeline-ui.yaml
index 585da03..2292966 100644
--- a/data-science-pipelines/overlays/ds-pipeline-ui/deployments/ds-pipeline-ui.yaml
+++ b/data-science-pipelines/overlays/ds-pipeline-ui/deployments/ds-pipeline-ui.yaml
@@ -30,7 +30,7 @@ spec:
             - --cookie-secret=SECRET
             - '--openshift-delegate-urls={"/": {"resource": "services", "verb": "get", "name": "ds-pipeline-ui"}}'
             - --skip-auth-regex='(^/metrics|^/apis/v1beta1/healthz)'
-          image: registry.redhat.io/openshift4/ose-oauth-proxy:v4.8
+          image: 'image-registry.openshift-image-registry.svc:5000/openshift/oauth-proxy:v4.4'
           ports:
             - containerPort: 8443
               name: https
diff --git a/data-science-pipelines/overlays/metadata-store-mariadb/kustomization.yaml b/data-science-pipelines/overlays/metadata-store-mariadb/kustomization.yaml
index 282a7fb..d0e9d19 100644
--- a/data-science-pipelines/overlays/metadata-store-mariadb/kustomization.yaml
+++ b/data-science-pipelines/overlays/metadata-store-mariadb/kustomization.yaml
@@ -23,5 +23,5 @@ generatorOptions:
 
 images:
   - name: mysql
-    newName: registry.redhat.io/rhel8/mariadb-103
-    newTag: "1-188"
+    newName: 'image-registry.openshift-image-registry.svc:5000/openshift/mariadb'
+    newTag: "10.3-el8"
diff --git a/data-science-pipelines/overlays/metadata-store-mariadb/persistentvolumeclaims/mariadb-pv-claim.yaml b/data-science-pipelines/overlays/metadata-store-mariadb/persistentvolumeclaims/mariadb-pv-claim.yaml
index e1fe730..443456e 100644
--- a/data-science-pipelines/overlays/metadata-store-mariadb/persistentvolumeclaims/mariadb-pv-claim.yaml
+++ b/data-science-pipelines/overlays/metadata-store-mariadb/persistentvolumeclaims/mariadb-pv-claim.yaml
@@ -5,6 +5,7 @@ metadata:
     application-crd-id: data-science-pipelines
   name: mariadb-pv-claim
 spec:
+  storageClassName: nfs-research
   accessModes:
     - ReadWriteOnce
   resources:
diff --git a/data-science-pipelines/overlays/metadata-store-mysql/persistentvolumeclaims/mysql-pv-claim.yaml b/data-science-pipelines/overlays/metadata-store-mysql/persistentvolumeclaims/mysql-pv-claim.yaml
index 3ef3625..776a1dc 100644
--- a/data-science-pipelines/overlays/metadata-store-mysql/persistentvolumeclaims/mysql-pv-claim.yaml
+++ b/data-science-pipelines/overlays/metadata-store-mysql/persistentvolumeclaims/mysql-pv-claim.yaml
@@ -5,6 +5,7 @@ metadata:
     application-crd-id: kubeflow-pipelines
   name: mysql-pv-claim
 spec:
+  storageClassName: nfs-research
   accessModes:
     - ReadWriteOnce
   resources:
diff --git a/data-science-pipelines/overlays/metadata-store-postgresql/persistentvolumeclaims/postgresql-pv-claim.yaml b/data-science-pipelines/overlays/metadata-store-postgresql/persistentvolumeclaims/postgresql-pv-claim.yaml
index 4222d32..ec05fbe 100644
--- a/data-science-pipelines/overlays/metadata-store-postgresql/persistentvolumeclaims/postgresql-pv-claim.yaml
+++ b/data-science-pipelines/overlays/metadata-store-postgresql/persistentvolumeclaims/postgresql-pv-claim.yaml
@@ -5,6 +5,7 @@ metadata:
     application-crd-id: kubeflow-pipelines
   name: postgresql-pv-claim
 spec:
+  storageClassName: nfs-research
   accessModes:
   - ReadWriteOnce
   resources:
diff --git a/data-science-pipelines/overlays/object-store-minio/persistentvolumeclaims/minio-pvc.yaml b/data-science-pipelines/overlays/object-store-minio/persistentvolumeclaims/minio-pvc.yaml
index b7ef611..16ce4ec 100644
--- a/data-science-pipelines/overlays/object-store-minio/persistentvolumeclaims/minio-pvc.yaml
+++ b/data-science-pipelines/overlays/object-store-minio/persistentvolumeclaims/minio-pvc.yaml
@@ -5,6 +5,7 @@ metadata:
         application-crd-id: data-science-pipelines
     name: minio-pvc
 spec:
+    storageClassName: nfs-research
     accessModes:
         - ReadWriteOnce
     resources:
diff --git a/jupyterhub/jupyterhub/base/jupyterhub-configmap.yaml b/jupyterhub/jupyterhub/base/jupyterhub-configmap.yaml
index 17df6b2..ed5be4d 100644
--- a/jupyterhub/jupyterhub/base/jupyterhub-configmap.yaml
+++ b/jupyterhub/jupyterhub/base/jupyterhub-configmap.yaml
@@ -6,7 +6,7 @@ metadata:
   name: jupyterhub-cfg
 data:
   jupyterhub_config.py: ""
-
+  storage_class: nfs-research
   jupyterhub_admins: "admin"
   gpu_mode: ""
   singleuser_pvc_size: 2Gi
diff --git a/jupyterhub/jupyterhub/base/jupyterhub-db-dc.yaml b/jupyterhub/jupyterhub/base/jupyterhub-db-dc.yaml
index 4ba6a5d..d3e7beb 100644
--- a/jupyterhub/jupyterhub/base/jupyterhub-db-dc.yaml
+++ b/jupyterhub/jupyterhub/base/jupyterhub-db-dc.yaml
@@ -23,7 +23,7 @@ spec:
         sidecar.istio.io/inject: "true"
     spec:
       containers:
-      - image: registry.redhat.io/rhel8/postgresql-96
+      - image: 'image-registry.openshift-image-registry.svc:5000/openshift/postgresql:9.6-el8'
         env:
         - name: POSTGRESQL_USER
           value: jupyterhub
diff --git a/jupyterhub/jupyterhub/base/jupyterhub-db-pvc.yaml b/jupyterhub/jupyterhub/base/jupyterhub-db-pvc.yaml
index fd2d027..05bd181 100644
--- a/jupyterhub/jupyterhub/base/jupyterhub-db-pvc.yaml
+++ b/jupyterhub/jupyterhub/base/jupyterhub-db-pvc.yaml
@@ -2,7 +2,7 @@ apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
   annotations:
-    volume.beta.kubernetes.io/storage-class: null
+    volume.beta.kubernetes.io/storage-class: nfs-research
   name: jupyterhub-db
 spec:
   accessModes:
diff --git a/jupyterhub/jupyterhub/base/params.env b/jupyterhub/jupyterhub/base/params.env
index d33a14d..b9bdc97 100644
--- a/jupyterhub/jupyterhub/base/params.env
+++ b/jupyterhub/jupyterhub/base/params.env
@@ -1,4 +1,4 @@
-storage_class=
+storage_class=nfs-research
 s3_endpoint_url=
 trusted_ca_bundle_path=
 jupyterhub_groups_config=jupyterhub-default-groups-config
diff --git a/jupyterhub/notebook-images/overlays/cuda-11.0.3/cuda-build-job.yaml b/jupyterhub/notebook-images/overlays/cuda-11.0.3/cuda-build-job.yaml
index 0eccd4f..d41da7b 100644
--- a/jupyterhub/notebook-images/overlays/cuda-11.0.3/cuda-build-job.yaml
+++ b/jupyterhub/notebook-images/overlays/cuda-11.0.3/cuda-build-job.yaml
@@ -10,7 +10,7 @@ spec:
   template:
     spec:
       containers:
-        - image: registry.redhat.io/openshift4/ose-cli:v4.7
+        - image: 'image-registry.openshift-image-registry.svc:5000/openshift/cli:latest'
           volumeMounts:
             - name: cuda-ubi8-build-chain
               mountPath: /tmp/
diff --git a/model-mesh/overlays/odh-model-controller/manager/manager.yaml b/model-mesh/overlays/odh-model-controller/manager/manager.yaml
index 3a57600..dee2f5e 100644
--- a/model-mesh/overlays/odh-model-controller/manager/manager.yaml
+++ b/model-mesh/overlays/odh-model-controller/manager/manager.yaml
@@ -55,9 +55,9 @@ spec:
         resources:
           limits:
             cpu: 500m
-            memory: 128Mi
+            memory: 512Mi
           requests:
             cpu: 10m
-            memory: 64Mi
+            memory: 256Mi
       serviceAccountName: odh-model-controller
       terminationGracePeriodSeconds: 10
diff --git a/odh-dashboard/base/kustomization.yaml b/odh-dashboard/base/kustomization.yaml
index 58cef02..1521659 100644
--- a/odh-dashboard/base/kustomization.yaml
+++ b/odh-dashboard/base/kustomization.yaml
@@ -24,5 +24,5 @@ images:
   newName: quay.io/opendatahub/odh-dashboard
   newTag: v2.5.2
 - name: oauth-proxy
-  newName: registry.redhat.io/openshift4/ose-oauth-proxy
-  newTag: v4.8
+  newName: 'image-registry.openshift-image-registry.svc:5000/openshift/oauth-proxy'
+  newTag: v4.4
diff --git a/odh-notebook-controller/odh-notebook-controller/manager/manager.yaml b/odh-notebook-controller/odh-notebook-controller/manager/manager.yaml
index 69dab1d..760a6bc 100644
--- a/odh-notebook-controller/odh-notebook-controller/manager/manager.yaml
+++ b/odh-notebook-controller/odh-notebook-controller/manager/manager.yaml
@@ -21,7 +21,7 @@ spec:
           imagePullPolicy: Always
           command:
             - /manager
-          args: ["--oauth-proxy-image", "registry.redhat.io/openshift4/ose-oauth-proxy:v4.10"]
+          args: ["--oauth-proxy-image", 'image-registry.openshift-image-registry.svc:5000/openshift/oauth-proxy:v4.4']
           securityContext:
             allowPrivilegeEscalation: false
           ports:
```
