### ISSUE TITLE
Add a second tag on base ImageStreams to support a second version of the image

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/odh-manifests#745]
Update ImageStreams objects for the core images to have a second tag in order to support one more updated version of the image

**Comment by shalberd** [comment]
if you do this the way you currently do it in the pull request, 
you potentially make airgapped / disconnected installs that rely on unique and unchanging image references via SHA256 digest more complicated or even impossible again ... tag.from.name should reference in digest.format.
If anything, when you add a second actual, more dynamic weekly imagestream tag that then points to the new sha256 image value.
https://github.com/opendatahub-io/odh-manifests/blob/4aa21564b0f23b413b63e5766677b6f6e39c6af9/notebook-images/base/jupyter-datascience-notebook-imagestream.yaml#L24

Name the imagestream tag-value to equal the image-tag value in the from.name.
e.g. from
```
from:
      kind: DockerImage
      name: quay.io/opendatahub/workbench-images:jupyter-datascience-ubi9-python-3.9-2023a-weekly
    name: "py3.9-v2"
```
to
```
from:
      kind: DockerImage
      name: quay.io/opendatahub/workbench-images@sha256:655f961295409d0d3a14927123ead8fff1b50b966948bcf18d10909e3ab32954
    name: "jupyter-datascience-ubi9-python-3.9-2023a-weekly"
```
![Bildschirmfoto 2023-03-24 um 18 27 28](https://user-images.githubusercontent.com/21118431/227597923-dda2848c-0868-4fce-88d7-df030818d964.png)

That way, you have visibility as to what the actual tag is and only need to ensure you update the digest-value in from.name as the tag changes from week to week.

Plus, we have ImageContentSourcePolicy and airgapped / disconnected support.

I have talked about this issue in another context with @VaishnaviHire 

`[Background](https://bugzilla.redhat.com/show_bug.cgi?id=1741391)`:

Description of problem:
In disconnected environments, CRIO uses the imagecontentsourcepolicy to "fallback" to alternate registry sources when pulling sha-based image specs.

The imagestream import controller should do the same, again only when importing a SHA based imagestreamtag.  If the external references is a SHA, and the import against the original registry fails, it should use the imagecontentsourcepolicy to try alternate registry sources to import the SHA.

If it succeeds, then the "status" for the tag should reflect the alternate registry.

@Jooho Can you tell us your opinion, please? See the suggested changes in the linked PR.
