### ISSUE TITLE
bug: notebook logout fails in Service Mesh branch

### ISSUE THREAD

**Issue by cam-garrison** [opendatahub-io/odh-manifests#877]
Pulling from https://issues.redhat.com/browse/OSSM-4385

**Describe the bug**
User logout functionality in the data science project's notebook is not working as expected. Clicking on the "Log Out" option under File menu displays an error message, and the link to the dashboard does not perform the desired action. The issue seems to be related to the Notebook resource and an incorrect logout URL defined in the annotation.

**Steps To Reproduce**
1. Create a data science project with a workbench defined.
2. Open it.
3. Go to File > Log Out menu

**Expected behavior**
The user should be logged out successfully and redirected to the desired location.

**Open Data Hub Version**
```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
 name: odh-mesh
spec:
 applications:
 - kustomizeConfig:
      parameters:
        - name: namespace
          value: istio-system
        - name: name
          value: minimal
      repoRef:
        name: manifests
        path: service-mesh/control-plane
   name: control-plane
 - kustomizeConfig:
      parameters:
        - name: namespace
          value: auth-provider
      repoRef:
        name: manifests
        path: service-mesh/authorino
   name: authorino
 - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
   name: odh-common
 - kustomizeConfig:
      overlays:
        - service-mesh
        - dev
      repoRef:
        name: manifests
        path: odh-dashboard
   name: odh-dashboard
 - kustomizeConfig:
      overlays:
        - service-mesh
      repoRef:
        name: manifests
        path: odh-notebook-controller
   name: odh-notebook-controller
 - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-project-controller
   name: odh-project-controller
 - kustomizeConfig:
      repoRef:
        name: manifests
        path: notebook-images
   name: notebook-images
 repos:
 - name: manifests
   uri: https://github.com/opendatahub-io/odh-manifests/tarball/service-mesh-integration
 version: service-mesh-integration
```
**OpenShift Version**
Version #: 4.12.13
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...): CRC

**Additional context**
